import { StyleSheet } from "react-native";
import { colors, spacing, radius, fontSize } from "../config/theme";

export const styles = StyleSheet.create({
  sessionBar:       { marginBottom: spacing.md },
  sessionRow:       { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sessionLeft:      { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  sessionText:      { fontSize: fontSize.base, fontWeight: "600" },
  sessionBtn:       { borderWidth: 1, borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  layout:           { flexDirection: "row", gap: spacing.md, flexWrap: "wrap" },
  leftPanel:        { flex: 2, minWidth: 280 },
  rightPanel:       { flex: 1, minWidth: 260 },
  searchRow:        { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.sm },
  searchBox:        { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.xs, backgroundColor: colors.bg, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.sm },
  searchInput:      { flex: 1, color: colors.text, fontSize: fontSize.base, height: 38 },
  barcodeBtn:       { backgroundColor: colors.scanner, borderRadius: radius.md, paddingHorizontal: spacing.md, justifyContent: "center" },
  barcodeBtnText:   { color: colors.bg, fontWeight: "700", fontSize: fontSize.md },
  productGrid:      { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.sm },
  productCard:      { width: "30%", minWidth: 90, backgroundColor: colors.bg, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.sm, alignItems: "center" },
  productName:      { fontSize: fontSize.sm, color: colors.text, textAlign: "center", marginBottom: 2 },
  productPrice:     { fontSize: fontSize.md, color: colors.pos, fontWeight: "700" },
  productUnit:      { fontSize: fontSize.xs, color: colors.textMuted },
  cartItem:         { flexDirection: "row", alignItems: "center", paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border + "40", gap: spacing.sm },
  cartName:         { fontSize: fontSize.md, color: colors.text, fontWeight: "600" },
  cartPrice:        { fontSize: fontSize.xs, color: colors.textMuted },
  qtyRow:           { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  qtyBtn:           { backgroundColor: colors.border, borderRadius: radius.sm, padding: 4 },
  qtyText:          { fontSize: fontSize.base, color: colors.text, minWidth: 20, textAlign: "center" },
  removeBtn:        { padding: 4 },
  totalsBox:        { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.md, paddingTop: spacing.md },
  totalRow:         { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.xs },
  totalLabel:       { fontSize: fontSize.md, color: colors.textDim },
  totalVal:         { fontSize: fontSize.md, color: colors.text },
  totalFinal:       { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.xs, paddingTop: spacing.sm },
  totalFinalLabel:  { fontSize: fontSize.lg, color: colors.text, fontWeight: "700" },
  totalFinalVal:    { fontSize: fontSize.xl, color: colors.primary, fontWeight: "700" },
  inlineInput:      { backgroundColor: colors.bg, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.sm, paddingVertical: 2, color: colors.text, fontSize: fontSize.md, width: 60, textAlign: "right" },
  modeRow:          { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.sm },
  modeBtn:          { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingVertical: spacing.sm, alignItems: "center" },
  modeBtnActive:    { backgroundColor: colors.primary, borderColor: colors.primary },
  modeBtnText:      { fontSize: fontSize.md, color: colors.textDim, fontWeight: "600" },
  changeText:       { fontSize: fontSize.md, color: colors.primary, fontWeight: "600", marginTop: spacing.xs },
  checkoutBtn:      { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm, backgroundColor: colors.pos, borderRadius: radius.md, padding: spacing.md, marginTop: spacing.lg, height: 48 },
  checkoutBtnText:  { color: colors.bg, fontSize: fontSize.base, fontWeight: "700" },
  modalHeader:      { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.lg },
  modalTitleText:   { fontSize: fontSize.lg, fontWeight: "700", color: colors.text },
  receiptHeader:    { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  receiptCode:      { fontSize: fontSize.lg, color: colors.primary, fontWeight: "700", marginBottom: spacing.sm },
  receiptTotal:     { fontSize: fontSize.xl, color: colors.text, fontWeight: "700" },
  receiptMode:      { fontSize: fontSize.md, color: colors.textDim, marginBottom: spacing.sm },
  receiptItem:      { flexDirection: "row", justifyContent: "space-between", paddingVertical: spacing.xs, borderBottomWidth: 1, borderBottomColor: colors.border + "40" },
  receiptItemName:  { fontSize: fontSize.md, color: colors.text },
  receiptItemVal:   { fontSize: fontSize.md, color: colors.textDim },
});
